#!/bin/bash
service pcscd stop
chkconfig pcscd off
service portmap stop
chkconfig portmap off
service nfslock stop
chkconfig nfslock off
service rpcidmapd stop
chkconfig rpcidmapd off
service yum-updatesd stop
chkconfig yum-updatesd off
service avahi-daemon stop
chkconfig avahi-daemon off
service autofs stop
chkconfig autofs off
service acpid stop
chkconfig acpid off
service atd stop
chkconfig atd off
service gpm stop
chkconfig gpm off
service haldaemon stop
chkconfig haldaemon off
service hidd stop
chkconfig hidd off
service irqbalance stop
chkconfig irqbalance off
service auditd  stop
chkconfig auditd off
service xfs stop
chkconfig xfs off
service cups stop
chkconfig cups off
service bluetooth stop
chkconfig bluetooth off
service anacron stop
chkconfig anacron off
